import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NewsMarquee from '@/components/NewsMarquee'
import Navbar from '@/components/Navbar'
import HomeComnponent from '@/components/Home'
import TrendingCoins from '@/components/TrendingCoins'
import React from "react"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
        
        <div className=' flex justify-evenly flex-wrap gap-10'>
          <NewsMarquee />

          <div className='w45rem'>
            <TrendingCoins />
            <HomeComnponent />
          </div>

        </div>

      </div>

    </>
  )
}
